export const baseRules = {
  // Base ESLint rules from your config
  'no-await-in-loop': 'error',
  'no-debugger': 'warn',
  'no-duplicate-imports': 'off',
  'no-inner-declarations': 'error',
  'no-promise-executor-return': 'error',
  'no-template-curly-in-string': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unreachable-loop': 'warn',
  'no-use-before-define': 'error',
  'no-useless-assignment': 'error',
  'require-atomic-updates': 'error',
  'arrow-body-style': ['error', 'as-needed'],
  'block-scoped-var': 'error',
  'complexity': ['error', { max: 10, variant: 'modified' }],
  'consistent-return': 'error',
  'curly': 'error',
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'eqeqeq': 'error',
  'func-style': ['error', 'expression'],
  'id-length': ['error', { min: 3, properties: 'never', exceptions: ['e', 'a', 'b', 'id'] }],
  'logical-assignment-operators': ['error', 'never'],
  'max-depth': ['warn', 2],
  'max-lines-per-function': [
    'warn',
    {
      max: 260,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  'max-lines': [
    'warn',
    {
      max: 300,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  'max-nested-callbacks': ['error', 3],
  'max-params': ['error', 3],
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-console': 'warn',
  'no-delete-var': 'error',
  'no-div-regex': 'error',
  'no-else-return': 'error',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-implicit-coercion': ['error', { allow: ['!!'] }],
  'no-implied-eval': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-magic-numbers': [
    'error',
    {
      ignoreArrayIndexes: true,
      ignoreDefaultValues: true,
      ignoreEnums: true,
      ignore: [-1, 0, 1],
    },
  ],
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-restricted-imports': [
    'error',
    {
      patterns: ['*/**/index'],
    },
  ],
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-self-assign': ['error', { props: true }],
  'no-sequences': 'error',
  'no-shadow': 'error',
  'no-shadow-restricted-names': 'error',
  'no-throw-literal': 'error',
  'no-undefined': 'error',
  'no-unneeded-ternary': 'error',
  'no-unused-vars': 'off',
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'object-shorthand': 'error',
  'one-var': ['error', 'never'],
  'operator-assignment': ['error', 'always'],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-destructuring': [
    'error',
    {
      array: false,
      object: true,
    },
    {
      enforceForRenamedProperties: false,
    },
  ],
  'prefer-exponentiation-operator': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'radix': ['error', 'as-needed'],
  'require-await': 'error',
  'yoda': ['error', 'never', { exceptRange: true }],
};
